
const actionTypes ={

    GET_ALL_PRODUCTS:'GET_ALL_PRODUCTS',
    ADD_SINGLE_PRODUCT:'ADD_SINGLE_PRODUCT',
    DELETE_SINGLE_PRODUCT:'DELETE_SINGLE_PRODUCT',
    EDIT_SINGLE_PRODUCT:'EDIT_SINGLE_PRODUCT',
    EDIT_SINGLE_PRODUCT_ACTUAL:'EDIT_SINGLE_PRODUCT_ACTUAL'
}

export default actionTypes;